config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
    # Authentication routes
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  get 'logout', to: 'sessions#destroy'
  
  # Resources
  resources :users
  
  resources :professors
  
  resources :rooms do
    member do
      get 'confirm_reassign'
    end
  end
  
  resources :disciplines do
    member do
      post 'enroll'
      delete 'unenroll'
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FAKE SIGA UFPR</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet">
</head>

<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark mb-4">
    <div class="container">
      <a class="navbar-brand" href="<%= root_path %>">FAKE SIGA UFPR</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav me-auto">
          <li class="nav-item">
            <a class="nav-link" href="<%= root_path %>">Início</a>
          </li>
          <% if logged_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%= disciplines_path %>">Disciplinas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= professors_path %>">Professores</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= rooms_path %>">Salas</a>
            </li>
            <% if admin? %>
              <li class="nav-item">
                <a class="nav-link" href="<%= users_path %>">Usuários</a>
              </li>
            <% end %>
          <% end %>
        </ul>
        <ul class="navbar-nav">
          <% if logged_in? %>            <li class="nav-item">
              <span class="nav-link">Bem-vindo, <%= current_user.name %> (<%= current_user.admin? ? 'Administrador' : 'Aluno' %>)</span>
            </li>
            <li class="nav-item">
              <%= link_to "Sair", logout_path, class: "nav-link" %>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= login_path %>">Entrar</a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

  <div class="container">
    <% if flash[:notice] %>
      <div class="alert alert-success">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <% if flash[:alert] %>
      <div class="alert alert-danger">
        <%= flash[:alert] %>
      </div>
    <% end %>

    <%= yield %>
  </div>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>